// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjepQwJKG8nJrgV-56chHMpk0h844sHmI',
    appId: '1:883536780495:android:45c149bb8dd9965b432bba',
    messagingSenderId: '883536780495',
    projectId: 'my-notes-a1eb6',
    storageBucket: 'my-notes-a1eb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK63_C5vGm9TxQpDKCC6G7b6jkJfgPu6M',
    appId: '1:883536780495:ios:ee1e4c8bb0d88456432bba',
    messagingSenderId: '883536780495',
    projectId: 'my-notes-a1eb6',
    storageBucket: 'my-notes-a1eb6.firebasestorage.app',
    androidClientId:
        '883536780495-kvlpa7vm9h2q4dn6t5bje2m2qh8c0qke.apps.googleusercontent.com',
    iosClientId:
        '883536780495-3o7hvd440bl1d21b1lqnqusc0fs0u9qc.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK63_C5vGm9TxQpDKCC6G7b6jkJfgPu6M',
    appId: '1:883536780495:ios:ee1e4c8bb0d88456432bba',
    messagingSenderId: '883536780495',
    projectId: 'my-notes-a1eb6',
    storageBucket: 'my-notes-a1eb6.firebasestorage.app',
    androidClientId:
        '883536780495-kvlpa7vm9h2q4dn6t5bje2m2qh8c0qke.apps.googleusercontent.com',
    iosClientId:
        '883536780495-3o7hvd440bl1d21b1lqnqusc0fs0u9qc.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNotes',
  );
}
